# Generated by Django 5.1.6 on 2025-03-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
